name: Checks

on:
  pull_request:
    branches: ["main"]
  workflow_call:

permissions:
  contents: read

jobs:
  Checks-and-Tests:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v6

      - name: Validate Build
        run: cargo build

      - name: Check Formatting
        run: cargo fmt --check

      - name: Clippy!
        run: cargo clippy --no-deps --all-targets

      - name: Run Tests
        run: cargo test
